/**:
  ros__parameters:

    ns: [ "right", "left" ]

    ### input topic info, (yaw,pitch,roll in degree/ x,y,z in meter)
    in_clouds:
      front:
        pose_yaw: 0.0
        pose_pitch: 0.0
        pose_roll: 0.0
        pose_x: 0.0
        pose_y: 0.0
        pose_z: 0.0
      rear:
        pose_yaw: 0.0
        pose_pitch: 0.0
        pose_roll: 0.0
        pose_x: 0.0
        pose_y: 0.0
        pose_z: 0.0

    out_cloud:
      frame_id: "base_link"
      period_ms: 100
      # rate: 10 # Hz
