/**:
  ros__parameters:

    ns: [ "front", "rear" ]

    ### input topic info, (yaw,pitch,roll in degree/ x,y,z in meter)
    in_clouds:
      # front: # vertical
      #   pose_yaw: 0.0
      #   pose_pitch: 0.0
      #   pose_roll: 0.0
      #   pose_x: 1.287
      #   pose_y: 0.0
      #   pose_z: 1.59762 # lowest: 1.50762 (0.09)
      # rear: # vertical
      #   pose_yaw: 0.0
      #   pose_pitch: 0.0
      #   pose_roll: 0.0
      #   pose_x: 0.359
      #   pose_y: 0.0
      #   pose_z: 1.59762 # lowest: 1.50762 (0.09)
      front: # tilting +10
        pose_yaw: 0.0
        pose_pitch: 10.0
        pose_roll: 0.0
        pose_x: 1.295790070872
        pose_y: 0.0
        pose_z: 1.596850968305 # lowest: 1.506850968305 (0.09)
      rear: # tilting -10
        pose_yaw: 0.0
        pose_pitch: -10.0
        pose_roll: 0.0
        pose_x: 0.350209929128
        pose_y: 0.0
        pose_z: 1.596850968305 # lowest: 1.506850968305 (0.09)

    out_cloud:
      frame_id: "base_link"
      period_ms: 100
      # rate: 10 # Hz
      use_deblurring: true
